### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#144]
If there are already unit tests commented out on any file you are working on, feel free to use/revamp them or replace them

‼️ *~* **Please comment below on this issue or add your name to a task on this list below if you plan to work on a task so we don't duplicate effort** *~* ‼️ 

OVERALL TEST COVERAGE: 76.8%

### **tbl_genomic() tests** - _priority_

- Add tests for deprecation errors
- Passing gene_binary explicitly: tbl_genomic(gene_binary = gene_binary) may cause error in some cases. I commented out this test for now, but we should revisit.
- Review rules for wrapper functions for tbl_summary (see {gtreg} as an example).
- May need more tests of other_vars arguments
- Read vignette updates to make sure they make sense

### **Test sanitize_data() functions in utils.R** 
- [ ] line 24 check if cli_abort works for missing columns
- [ ] line 37 clin_abort fusions in mutation data frame
- [ ] lines 44-45 mutation status in column names warning
- [ ] all of if variant_type is in column names loop
- [ ] lines 111 abort if no sample ID found
- [ ] lines 117 abort if no hugo symbol column found
- [ ] 159-160 abort if number of missing columns is > 0

### **Here are some steps to help you get started contributing to this effort at the hackathon:** (left from previous version of issue in case we need it later)

1.  If you've never written unit tests, here is a great resource to skim in order to get an introduction to testing https://r-pkgs.org/tests.html 
2. Fork, clone and branch the repository (see github trainings)
3. Once you've done the above to get your own copy,  check that you can install the package and run checks ("Build" tab in RStudio). Try checking the package test coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. This will show you the test coverage of each file and the package overall. One of our goals is to increase this coverage percentage. 
4. Read the documentation for the argument you are testing (it might also need updating). 
5. Start writing tests with correctly specified args passed and also incorrect args passed. Check the following, as well as any common user behavior you can think of: 
    - When you specify the argument correctly (according to the documentation) does it return what you would expect ? 
    - When you don’t specify the argument at all, does it return what you expect?
    - When you incorrectly specify the arg, does it give you a useful warning or message?
    
Additionally, I've added some suggestions for tests in the test files themselves (in the tests folder of the package)

6. Please add tests to the tests R files (in test folder). For tests you can use internal data (e.g `gnomerR::mut`, `gnomerR::fusion`, `gnomerR::cna`), a small sample of real data, or create your own fake data.
7. Additionally, if the function is working as expected but the function documentation is not clear, please edit the documentation (R folder in package).  If any functions don’t work as expected, please make or suggest a change to the documentation or the function itself. If you can fix it yourself, please submit a PR with a change. For example, if you think the error/warning messages are unclear, please add warnings to the function. If you can’t fix it yourself, no problem, but please file an issue for your suggestion so we can make sure to address it!

**Comment by ChristineZ-msk** [comment]
I'll join this. Try to learn binary_matrix() and see if I can add an unit test there.

**Comment by karissawhiting** [comment]
Thanks @ChristineZ-msk for addressing some of these in #156, they look great! 

Checking off the ones we've covered above. Please add notes here or in a new issue if you come across anything in testing that needs changing. 

I think we should add a warning to `binary_matrix()` when `snp_only = TRUE` and there are some NA's for `Variant_Type` 
 that are being filtered out. Something like "X alterations with unknown variant type were filtered out. To return all, pelase set snp_only = FALSE".

**Comment by ChristineZ-msk** [comment]
@karissawhiting:  I totally agree a warning should be added to binary_matrix() when snp_only = TRUE and there are some NA's for Variant_Type. And I see you already merge my added unit test to the master. So if I am keep working on adding unit test to binary_matrix() or some other function you listed under this issue (i.e. if I have time, I want to check some plotting functions), do I need to re-clone from master?

**Comment by karissawhiting** [comment]
You will need to pull in new changes from yesterday into your fork so you have the most up to date version. Then you can create a new branch for any new changes. You can delete the old branch now that it’s merged.

**Comment by ChristineZ-msk** [comment]
Great to know. Thank you. I'll leave comment here if I notice any issue I come across during checking.

**Comment by ChristineZ-msk** [comment]
@karissawhiting: I found some issue when I try to add unit test to args of `binary_matrix()` today. I list them below:

1. In `binary_matrix()` , when the `Variant_Classification` is NA, if `include_silent = F` then 0 column result will be returned with no warning. If if `include_silent = T` then full list result will be returned with no warning. Maybe warning should be added to ` include_silent = F ` situation? 

2. In `binary_matrix()`, if we choose `cna_relax=F`, it seems the “.Amp” value is correct (i.e. considering only 2 instead 1 and 2), but for “.Del”, it seems both -1 and -2 are considered as “deletion” instead of only considering "-2" as deletion event we choose `cna_relax=F`. I don't know if that is correct or not.

3. I don’t quite understand what the `rm_empty` does. It seems, that if there is no event (al 0) in one of the columns found in the results, if set `rm_empty = T` then that column should be removed and if set `rm_empty = F` then then that column should be kept in the final results (even there is no event in this gene). Maybe I am wrong. 

    Please run the following code, then you can understand what I am puzzling about:
`cna_try<-gnomeR::cna[1:6,1:10]`  #this is a all 0 cna data
`cna_try[c(1,3),c(2,5)]<-(-2)`
`cna_try[c(2,4,5),c(3,9)]<-2`
`binary_matrix( cna= cna_try, rm_empty=F)`
`binary_matrix( can= can_try, rm_empty=T)`

First, the no event gene “ALT” is not kept if using `rm_empty = F`; second, when using `rm_empty = T` the non-zero event column “ABL1.Del” is removed.

**Comment by hfuchs5** [comment]
As of 9/21 here is the coverage report:
![image](https://github.com/MSKCC-Epi-Bio/gnomeR/assets/100386516/b3058fba-5f3e-425e-897c-6183d320d33b)
*NOTE Nick did plotting functions and we haven't merged them in yet
