### ISSUE TITLE
Add helper function to paste/remove endings on gene names (.Amp, .fus etc)

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#212]

**Comment by hfuchs5** [comment]
Look at add_pathways() function where ".mut" is pasted to hugo symbol names

**Comment by hfuchs5** [comment]
```
function(x) {
        x[!str_detect(x, ".Amp|.Del|.fus|.cna")] <-
          paste0(stringr::str_trim(
            x[!str_detect(x, ".Amp|.Del|.fus|.cna")]), ".mut")

x <- c("TERT", "APC.Amp", "MYC.fus", "PTEN.Del")
```

**Comment by karissawhiting** [comment]
@hfuchs5  I'm actually about to change it there not sure to what yet! This function will be used in `summarize_by_gene()` and maybe still pathways. Maybe still in `tbl_genomic()`?

**Comment by hfuchs5** [comment]
a small function that takes in a data frame with different gene names as a variable (either no ending/.Amp/.Del/.fus ex: TERT.Amp) and separates them into a list of dataframes of each type

rough idea:
1. start with a vector or dataframe with gene names
2. create a function that will read the gene name endings and return a list object c(all_mutations, all_CNA, all_fus) (each one would be a character vector) so that the other functions can find these variables quickly.
