### ISSUE TITLE
GENIE BPC vignette 

### ISSUE THREAD

**Issue by hfuchs5** [MSKCC-Epi-Bio/gnomeR#215]
Talked to Sammi and this is a good dataset to use for a GENIE example. It will pull a maf file for us.

https://genie-bpc.github.io/genieBPC/articles/pull_data_synapse_vignette.html
nsclc_2_0 = pull_data_synapse("NSCLC", version = "v2.0-public")

**Comment by hfuchs5** [comment]
- [x] finish documenting new datasets in `data.R` file
- [x] add links to {genieBPC} documentation

**Comment by karissawhiting** [comment]
@hfuchs5 @slb2240 @jalavery The GENIE vingnette is now live and is looking pretty awesome 😎. 

‼️ https://mskcc-epi-bio.github.io/gnomeR/articles/genie-bpc-vignette.html 

 
Thank you for all your help. @slb2240 or @jalavery could one of you do a final review of it during the hackathon? I have a few comments/ suggestions that you can take or leave:

- I commented out the fusions data from the binary matrix to get it to run (I think reformat function wasn't updated yet) but this needs to be added back in eventually (@hfuchs5 ) 
- Can we move the paper references to the bottom as citations and then just link to them in a sentence at the top?
- May be good to add a short couple sentences at the top about why this data is different from other common data formats (e.g. comes from different sources, fusions formatted differently, different panels/alises used from different institutions)
- Add a little verbage on aliases and add custom alias section/code (@hfuchs5 ) 
- I added credentials to the repo secrets so we can run the data pull functions but maybe we should add whatever checks you had in genieBPC vignette for pull data to prevent running vignette when not connected successfully to GENIE 
- In data format section we can link now to the section in the genieBPC vignette that describes specific differences between genomic data pulled from different formats
- There is one NA in `nsclc_2_0_sample_panels` that I had to remove before running the create_gene_binary code. Not sure if this is suppose to be there?
- I would consider adding a note explaining warning messages that result from `create_gene_binary()` (although I will be cleaning them up before the hackathon so hopefully less noticeable) 
- Can we do a comparison of dfs without {arsenal} package? If not I'm okay with it but would be nice to cut down on `suggests` in dependencies 
- I think we could just run the visualizations on one version of the data to make it more concise (but I don't feel strongly either way!)
- As of now the `summarize_by_gene()` section doesn't change the data because the data set only has mutations before passing to that, but this may not be the case once the fusions are added back. If it doesn't we should select columns with other types of alterations to show how this summarize function works.

Thanks all!
