### ISSUE TITLE
Check how point mutations or genes with a period are treated

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#269]

**Comment by hfuchs5** [comment]
I did this in my project with TERT.5flank and it worked fine with the annotations and `create_binary_matrix`

**Comment by hfuchs5** [comment]
add warning to say that any non-impact named genes then they won't be NA annotated

add test to make sure these columns are working properly

**Comment by hfuchs5** [comment]
check warnings with NA annotate and removing the all NA columns

**Comment by hfuchs5** [comment]
NOTE: these genes will be annotated with NA if a gene-panel is specified. People will have to make a separate gene_binary matrix and then cbind/left_join to the rest. 

Also, if a period is in the column name, there is some issue including the variable in a logistic regression model formula. Will have to rename to make it work, but this is not an issue we plan to address because it can be fixed with tidyverse.
