### ISSUE TITLE
error message in create_gene_binary specify_panel argument should be warning

### ISSUE THREAD

**Issue by hfuchs5** [MSKCC-Epi-Bio/gnomeR#304]
![image](https://github.com/MSKCC-Epi-Bio/gnomeR/assets/100386516/299e662f-4bcb-4670-be87-e1aa5769bfca)

Using the GENIE vignette as the repex. I don't think that this should halt the code. We can discuss later.

**Comment by karissawhiting** [comment]
I think this was fixed in the Genie data. 

After further thought, I'm thinking we should keep this as an error for now. In the GENIE example, this actually helped point out an error/missing data point that should have been there so maybe it's doing its job?

I'm open to re-opening this issue in the future if it comes up again as an annoyance to users.
